### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by vrx29**

### CODE REVIEW

**Review by Hamza-777 — APPROVED** [review]
You refactored the code I think it all looks good.

**Comment by Hamza-777** [comment]
Also if all the other import are in a separate css file and then that file is import into the main css file it will make it look more cleaner.

**Comment by vrx29** [comment]
Okay will fix this

**Review by Dev-AkshatGupta — APPROVED** [review]
That's great you have done a great job that you changed tags from the semantic HTML's

**Pull request merged**
