### PR TITLE
feat: added documentation pages

### PR DESCRIPTION
**Pull request by vrx29**
Live Preview: https://gimesto.netlify.app/

The component library is complete and live please give your suggestions and feedback.
Thanks

### CODE REVIEW

**Review by nayyyhaa — APPROVED** [review]
Nice work! UI looks clean and professional. 💯

**Review by BalajiHarinath — APPROVED** [review]

**Review by Developers-codz — APPROVED** [review]

**Comment by Developers-codz** [comment]
Amazing Work .

**Comment by BalajiHarinath** [comment]
Looks good to me. Your UI looks neat.

**Review by ParthParolekar — APPROVED** [review]
This looks great!

**Comment by sainath7878** [comment]
This is so so good. The hamburger is popping from the left, Would look great if pops from the top.

**Pull request merged**
